name: "SpeedTest"
version: "1.0.0"
slug: "SpeedTest"
description: "Checks internet connectivity and speed."
arch:
  - "armv7"
  - "armhf"
  - "aarch64"
  - "amd64"
  - "i386"
startup: "application"
boot: "auto"
ingress: false
options:
  ping_interval: 5  # Default: Check connectivity every 5 minutes
  speedtest_interval: 30  # Default: Run speed test every 30 minutes
  host: "8.8.8.8"  # Default: Google DNS for connectivity check
schema:
  ping_interval: int(min=1)
  speedtest_interval: int(min=5)
  host: str
