name: Grocy Item Scanner
version: 1.0.0
slug: grocy_itemscan
description: A barcode scanner for Grocy integration
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: application
ingress: true
panel_icon: mdi:barcode-scan
webui: "http://[HOST]:[PORT:8198]"
ports:
  8198/tcp: 8198
options:
  grocy_api_key: ""
  grocy_url: ""
  external_api_key: ""
schema:
  grocy_api_key: str
  grocy_url: url
  external_api_key: str
