name: Grocy Item Scanner
version: 1.0.0
slug: grocy_itemscan
description: A barcode scanner for Grocy integration
arch:
  - aarch64
  - amd64
  - armv7
  - i386
  - x86_64
startup: application
ingress: true
ingress_port: 8099
panel_icon: mdi:barcode-scan
panel_title: Grocy Scanner
webui: "http://[PROTO:tcp]://[HOST]:[PORT]"
ports:
  8099/tcp: 8099
schema:
  grocy_api_key:
    type: string
    description: Your Grocy API Key
  grocy_url:
    type: string
    description: Your Grocy URL
  external_api_key:
    type: string
    required: false
    description: Optional API key for external product database
options:
  grocy_api_key: ""
  grocy_url: ""
  external_api_key: ""
