name: Grocy Item Scanner
version: 1.0.0
slug: grocy_itemscan
description: An add-on for scanning items into Grocy, integrated with Home Assistant.
options:
  api_key: "YOUR_API_KEY"
  grocy_url: "http://your-grocy-instance"
schema:
  api_key: str
  grocy_url: str
panel:
  title: Grocy Scanner
  icon: mdi:barcode-scan
