name: Grocy Item Scanner
version: 1.0.0
slug: grocy_itemscan
description: A barcode scanner for Grocy integration
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: application
ingress: true
panel_icon: mdi:barcode-scan
webui: "[PROTO:http]://[HOST]:[PORT]"
ports:
  8099/tcp: 8099
schema:
  grocy_api_key:
    type: str
    description: API key
  grocy_url:
    type: url
    description: URL
  external_api_key:
    type: str
    description: API key
    required: false
options:
  grocy_api_key: ""
  grocy_url: ""
  external_api_key: ""
